---
- name: Upgrade pip
  command: >
    pip install --upgrade pip;
  become: no
  tags:
    - python

- name: Install python dependencies
  pip: name={{ item }} state=present
  with_items: "{{ pip_packages | default() }}"
  become: yes
  become_user: root
  tags:
    - python
