---
- name: Ensure pathogen directories exist
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim/autoload 
    - ~/.vim/bundle
  tags:
    - vim

- name: Install pathogen
  get_url: 
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim
    mode: 0644
  tags:
    - vim

- name: Clone vim themes
  git:
    repo: "{{ item.repo }}"
    dest: "~/.vim/bundle/{{ item.dest }}"
    accept_hostkey: no
    force: yes
  with_items:
    - { repo: "git://github.com/altercation/vim-colors-solarized.git", dest: vim-colors-solarized }
    - { repo: "git://github.com/roosta/srcery.git", dest: srcery }
  become: no
  tags:
    - vim
